### ISSUE TITLE
Error with running stress

### ISSUE THREAD

**Issue by parsa25eng** [openfun/bbb-stress-test#14]
Hi there,
I have install the package by the mentioned instructions. But when a I am  going to run the "make stress" the following error has appeared.

 Error: Failed to launch the browser process!
[0510/195146.876103:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

I will be so grateful if you guide me how I can resolve this error.
thank you.

**Comment by Fry-4TF1V** [comment]
Hi,
You have to install and run the "make stress" not as root

**Comment by 06dilipg** [comment]
> Hi,
> You have to install and run the "make stress" not as root

Hi,
@Fry-4TF1V , I ran "make stress" not as root,but still I face above mentioned issue,could you please elaborate the instructions to be followed,thank you.

**Comment by Fry-4TF1V** [comment]
Hi @06dilipg,

You can rely on some part of script I did few months ago which worked for me (did not test it recently) :


              "cd /tmp",
              "git clone https://github.com/openfun/bbb-stress-test.git",
              "sudo apt install make -y",
              "cd /tmp/bbb-stress-test/",
              "sudo add-apt-repository universe -y",
              "sudo apt update",
              "sudo apt install docker-compose -y",
              "make bootstrap",
              "sed -i 's/BBB_URL=.*/BBB_URL=https:\\/\\/${var.bbb_fqdn}\\/bigbluebutton\\//g' .env",
              "sed -i 's/BBB_SECRET=.*/BBB_SECRET=${var.bbb_secret}/g' .env",
              "sed -i 's/BBB_MEETING_ID=.*/BBB_MEETING_ID='$(sudo make list-meetings | grep participants | head -n 1 | awk '{print $3}')'/g' .env",
              "sed -i 's/BBB_TEST_DURATION=.*/BBB_TEST_DURATION=${var.params.duration}/g' .env",
              "sed -i 's/BBB_CLIENTS_LISTEN_ONLY=.*/BBB_CLIENTS_LISTEN_ONLY=${var.params.listen_only}/g' .env",
              "sed -i 's/BBB_CLIENTS_MIC=.*/BBB_CLIENTS_MIC=${var.params.micro}/g' .env",
              "sed -i 's/BBB_CLIENTS_WEBCAM=.*/BBB_CLIENTS_WEBCAM=${var.params.webcam}/g' .env",
              "make stress",


This script is based on [this file](https://github.com/Fry-4TF1V/bbb_stresstest_with_terraform/blob/90cb6086039807c7c61a18f777df053ed1e05340/main.tf)

**Comment by 06dilipg** [comment]
> Hi @06dilipg,
> 
> You can rely on some part of script I did few months ago which worked for me (did not test it recently) :
> 
> ```
>           "cd /tmp",
>           "git clone https://github.com/openfun/bbb-stress-test.git",
>           "sudo apt install make -y",
>           "cd /tmp/bbb-stress-test/",
>           "sudo add-apt-repository universe -y",
>           "sudo apt update",
>           "sudo apt install docker-compose -y",
>           "make bootstrap",
>           "sed -i 's/BBB_URL=.*/BBB_URL=https:\\/\\/${var.bbb_fqdn}\\/bigbluebutton\\//g' .env",
>           "sed -i 's/BBB_SECRET=.*/BBB_SECRET=${var.bbb_secret}/g' .env",
>           "sed -i 's/BBB_MEETING_ID=.*/BBB_MEETING_ID='$(sudo make list-meetings | grep participants | head -n 1 | awk '{print $3}')'/g' .env",
>           "sed -i 's/BBB_TEST_DURATION=.*/BBB_TEST_DURATION=${var.params.duration}/g' .env",
>           "sed -i 's/BBB_CLIENTS_LISTEN_ONLY=.*/BBB_CLIENTS_LISTEN_ONLY=${var.params.listen_only}/g' .env",
>           "sed -i 's/BBB_CLIENTS_MIC=.*/BBB_CLIENTS_MIC=${var.params.micro}/g' .env",
>           "sed -i 's/BBB_CLIENTS_WEBCAM=.*/BBB_CLIENTS_WEBCAM=${var.params.webcam}/g' .env",
>           "make stress",
> ```
> 
> This script is based on [this file](https://github.com/Fry-4TF1V/bbb_stresstest_with_terraform/blob/90cb6086039807c7c61a18f777df053ed1e05340/main.tf)


Hi @Fry-4TF1V,

All the above configurations are done. At the end, when i give the command "make stress" i'm getting below error:

ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
make: *** [Makefile:47: stress] Error 1

FYI: I'm installing the bbb-stress-test in different server and bigbluebutton is installed in different server.

**Comment by wahahmed15** [comment]
> Hi,
> You have to install and run the "make stress" not as root

How I can run this? 
I have below error:

root@localhost:/tmp/bbb-stress-test# make stress
🐳(entrypoint) creating user running in the container...
🐳(entrypoint) running your command: ./cli.js stress -v
info:    Starting stress test on meeting random-3199291
info:    Test parameters :
info:     - webcams : 10
info:     - microphones : 10
info:     - listening : 10
info:     - duration : 60s
Error: Failed to launch the browser process!
[0622/055827.904075:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/launcher/BrowserRunner.js:189:20)
    at Interface.helper_1.helper.addEventListener (/app/node_modules/puppeteer/lib/launcher/BrowserRunner.js:179:65)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mballinas** [comment]
Had the same issue, I edited the file lib/stress-test.js, added de arg "--no-sandbox" in the array declared on line 80:
`args: [
"--use-fake-device-for-media-stream",
"--use-fake-ui-for-media-stream",
"--mute-audio",
"--no-sandbox"
],`

Not sure if that was the best but it worked, now I'm facing the error mentioned here: https://github.com/openfun/bbb-stress-test/issues/11

**Comment by olwe0002** [comment]
I had the same problem, if you follow [this](https://docs.docker.com/engine/install/linux-postinstall/) steps to make it possible to run docker as non-root, and then go back to the very beginning to build the image and run the tests, everything works fine
