### ISSUE TITLE
Running as root without --no-sandbox is not supported. 

### ISSUE THREAD

**Issue by ralfsf007** [openfun/bbb-stress-test#9]
Hi, I have a problem I run sudo make stress and it gives thsi error:
Error: Failed to launch the browser process!
[0110/215548.567156:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

When I run without sudo it just gives me permission denied.

Can you advise?

**Comment by sampaccoud** [comment]
@ralfsf007 you shouldn't run it as root. Can you paste the permission denial here?

**Comment by ralfsf007** [comment]
> @ralfsf007 you shouldn't run it as root. Can you paste the permission denial here?

@sampaccoud Thank you for your reply. The reqested error:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'P                                                                                                             ermission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 205, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 228, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13,                                                                                                              'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connec                                                                                                             tion aborted.', PermissionError(13, 'Permission denied'))
[58180] Failed to execute script docker-compose
Makefile:47: recipe for target 'stress' failed
make: *** [stress] Error 255

**Comment by madmatah** [comment]
Hello @ralfsf007  

As a fast fix you can use the branch proposed in #8.
I'll propose another solution soon to avoid this error.

**Comment by ralfsf007** [comment]
@madmatah Hi, thank you that worked. 
Mybe you know where I can set timeout time aswell after few users successfully connect I get timeout error: Unable to initialize client K.C.2618 : TimeoutError: Navigation timeout of 30000 ms exceeded

**Comment by madmatah** [comment]
For the record, if others encounter this problem : we really encourage you not to run this project as root.
Can you run `docker ps` with your current user ? You should be able to.

If this is not the case, I invite you to follow the instructions here to be able to run docker as a non-root user: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
(You probably just have to add your user to the `docker` group and logout/log back in)

@ralfsf007 : for your question, you should be able to tweak this timeout as explained [here](https://ourcodeworld.com/articles/read/1106/how-to-solve-puppeteer-timeouterror-navigation-timeout-of-30000-ms-exceeded) by updating the code.
